### ISSUE TITLE
Streamlabs donation Alerts not working

### ISSUE THREAD

**Issue by chilledsheep** [BlackyWhoElse/streamer.bot-actions#101]
i have set Streamlabs donations in script.js to true but alerts do not work.

the console shows this when i trigger a test donation at streamlabs dashboard

```
donation
script.js:272 There is no variant defined for donation.
script.js:205 TypeError: Cannot read properties of undefined (reading 'donation')
    at renderAlert (script.js:163:47)
    at script.js:202:17
    at new Promise (<anonymous>)
    at pushAlert (script.js:195:12)
    at ws.onmessage (streamer.bot.js:49:25)
(anonymous) @ script.js:205
Promise.catch (async)
pushAlert @ script.js:204
ws.onmessage @ streamer.bot.js:49
script.js:240 Alert finished
```

**Comment by BlackyWhoElse** [comment]
Seems like there is a variable missing. I will make some tests with it and let you know once it's working

**Comment by BlackyWhoElse** [comment]
I just realized that you meant the alert widget. 
I haven't worked on that for a long time. 
This widget will be completely rewritten by me as it is based on an older version of streamer.bot,

 ToDo list:
- [ ] Documantaion
- [ ] Settings.json file
- [ ] Optimization of the pushAlert function

**Comment by chilledsheep** [comment]
How long will this take approximately? :)

**Comment by BlackyWhoElse** [comment]
> How long will this take approximately? :)
I will try to make a quick fix for you and then start with the rewrite.
I'm currently a bit short on time but I think i could be done by monday

**Comment by chilledsheep** [comment]
> > How long will this take approximately? :)
> 
> I will try to make a quick fix for you and then start with the rewrite. I'm currently a bit short on time but I think i could be done by monday

did you already had time for the quick fix?
