### ISSUE TITLE
[Bug] Imports not working with new Streamer.bot update

### ISSUE THREAD

**Issue by adrisdead** [BlackyWhoElse/streamer.bot-actions#105]
I can´t import any action in streamer.bot because of the 0.2.4 update. It shows a message attached below. Is it possible to update the collection or is there a workaround? I suppose that if i downgrade streamer.bot it will work?

Thanks for sharing this with the community!

![Screeenshot_1](https://github.com/user-attachments/assets/2c2890eb-7786-456d-958e-d7f8e53bae96)

**Comment by BlackyWhoElse** [comment]
I will update the imports soon. Thanks for sharing

**Comment by adrisdead** [comment]
You´re welcome, thank to you for your work

**Comment by BlackyWhoElse** [comment]
Hi o/ what action are you trying to import?

**Comment by BlackyWhoElse** [comment]
Oh, I see you mean inside the wiki files.
I will update the wiki. But most of these codes should already be in a .sb file inside the widgets or games.

**Comment by adrisdead** [comment]
I tried it today and everything works fine, thanks a lot!! 

I have only one question about "who´s that pokemon"; I was trying to change the chat responses to spanish and it was easy to find them in streamerbot, but there´s one that i can´t find in the streamerbot actions or the script. 

Is the first one that appears when triggering the !wtp command: "A new game of Who's that Pokemon just started. Guess the Pokemon by typing in chat!"

I didn´t know if i should open a new issue for that, sorry if this is not the place for asking!
