### ISSUE TITLE
[Bug] Changes in Script not taking effect (who´s that pokemon)

### ISSUE THREAD

**Issue by adrisdead** [BlackyWhoElse/streamer.bot-actions#106]
Hi!

I was trying to set up the "who´s that pokemon" game. Everything works fine except changing the settings. Probably i´m doing it wrong or missing something.

I´ve tried to change the language names to spanish or english and other settings of the script.js but none take effect. I opened the file with Notepad+ and saved it once the changes were made. Is there a extra step i´m missing?

Thanks!<3

**Comment by BlackyWhoElse** [comment]
Hey thanks for reporting. Will check on that in the next week.

**Comment by BlackyWhoElse** [comment]
Not sure why but there was code from an experimental branch inside the index.html
In this older version settings are controlled via the script.js file.

I removed the unnecessary code and will create a fix later this week. 
Thanks for reporting
