### ISSUE TITLE
[Bug] Animations with Chat Widget don't work. 

### ISSUE THREAD

**Issue by fizsgit** [BlackyWhoElse/streamer.bot-actions#107]
### Describe the bug
With the latest release (downloaded today, 19-SEP-2024), no animations play when text appears when using the chat widget. 

Neither the default theme or clean (only two tested) work. I know that changes are being made, I have changed the font and can see the change reflected when refreshing the Browser Source Cache in OBS. Animation settings are set to true and even when values for the animation or duration aren't touched, they don't work. 

Everything else seems to work, only the animations don't. the text doesn't fade out either when settings a fade time out.

### Screenshots
I will include the paths in the screenshots so you can see respective folder locations etc for each screenshot, they will also be labelled. 

Settings.json: 
![image](https://github.com/user-attachments/assets/c047c55f-4a0c-4f7d-b0ce-f9bf880984d9)

Default theme settings.json (unmodified) 
![image](https://github.com/user-attachments/assets/a64caf41-5906-4d3e-85bd-30dbd037a8ed)

clean theme settings.json (unmodified)
![image](https://github.com/user-attachments/assets/0b99a6f2-2036-4fc6-bcdc-7a85ea78ab81)

clean theme styles.cc (modified font and is working, also changed animation durant to 0.5s)
![image](https://github.com/user-attachments/assets/29f343d8-9ef9-41da-bfde-769f3f814c08)

Haven't modified any other files, fresh install as I've never used this before. Looks promising, would just like the animations to work. Hopefully it's a simple fix!

Thanks!

**Comment by fizsgit** [comment]
hide delay being in ms was throwing off the animations, hide delay and show animation was happening at the same time, hide animation cancelling out show animation hence issue. Resolved now!

**Comment by BlackyWhoElse** [comment]
I am currently working on an updated Wiki/README and will keep this in mind. That should be noted there

**Comment by fizsgit** [comment]
No bother! It is noted, and upon reading again (which is where I found that might be the issue) I tested and it actually works fine. Just forgot when setting up because other durations are in seconds and not ms! Works great though! Thanks for making it

**Comment by sqzneedhelp** [comment]
How did you fix this again?

**Comment by fizsgit** [comment]
> How did you fix this again?

Hey, There's a setting for the hide delay, this value is in ms which is different to other animation settings that are actually just in seconds. I would increase the hide delay to a value of 10000 to start (this is 10seconds) and see what happens after that!
