### ISSUE TITLE
[Bug] Messages are not deleted from Twitch Chat

### ISSUE THREAD

**Issue by eldemiandx** [BlackyWhoElse/streamer.bot-actions#113]
### Describe the bug
When a message is deleted from the chat, it is not deleted from the chat. The same happens if it is timeout and banned user.
If it was planned like that, it can become a trigger that each user can choose.

**Comment by BlackyWhoElse** [comment]
Is this also Youtube related?

**Comment by eldemiandx** [comment]
No, just Twitch.

I was told that YT doesn't send information when a post is deleted, but if you can get it done, that would be great.

**Comment by BlackyWhoElse** [comment]
Should be fixed in a04d7b0
