### ISSUE TITLE
[Feature] Youtube Chat messages need emote support

### ISSUE THREAD

**Issue by BlackyWhoElse** [BlackyWhoElse/streamer.bot-actions#56]
Currently chat messages from youtube are not loading emotes.
1. Find a way to load emotes
2. Add emote loading

**Comment by Haunter56** [comment]
Is the challenge with getting the links for the YouTube emojis? Or just getting it to show in the widget? I think I have a list of IDs for all of them. Not sure if that is helpful.

**Comment by BlackyWhoElse** [comment]
> Is the challenge with getting the links for the YouTube emojis? Or just getting it to show in the widget? I think I have a list of IDs for all of them. Not sure if that is helpful.

Hello @Haunter56
I haven't worked on that for a long time. I will look into this feature in the near future when I have a bit of time to stream to youtube.
