### ISSUE TITLE
[Game] Wordle 

### ISSUE THREAD

**Issue by BlackyWhoElse** [BlackyWhoElse/streamer.bot-actions#69]
Suggested by **Poodmund#8008**
— 
07.12.2022 - 23:40 Uhr
Using the WebSocket, can you detect raw input (input message) from a Twitch Channel Point redemption for use in something like a custom StreamElements widget Javascript variable?

Was thinking of trying to convert this  [CodePen](https://codepen.io/Poodmund/pen/bGKZGaE) to monitor a channel redemption input to guess the word but have it nicely wrapped up into a single browser source.

**Comment by Poodmund** [comment]
Just stumbled across this and thought that it was another nice example. https://codepen.io/pbutcher/pen/oNogxZW

**Comment by BlackyWhoElse** [comment]
Prepping for Stream:
bd36eb7
9ce831b
ae39fd6

**Comment by Poodmund** [comment]
Hi, testing it out in VSCode and have also made it into a browser source overlay via StreamElements. Working really nicely! 😄 Thought I'd post my findings here:

Issue:
- If you guess a word that doesn't exist within the word list library (some made up word i.e. asdfg), the game enters the 'non-word', shakes and then stops. You can't enter any more guesses. I think that at the stage that the JS gets to this stage: rowEl.dataset.state = "invalid"; the game needs to wait a few seconds and then delete the entered keys one by one to then allow for another guess to be made.

Enhancements:
- Currently, the game does not show which letters have already been used in the guesses. In the real Wordle game, a QWERTY keyboard is shown underneath the 6 rows of guesses and if you use a letter in a guess, it greys out that letter on the QWERTY keyboard to show the user that its been used. If that could be replicated it would be amazing. EDIT: I just realised that this is based of the Peter Butcher Wordle clone that has the keyboard there.
- Be able to send a command to be able to do the following:
  - Send a command to reset the game
  - Send a command to hide the game (fade it out)
  - Send a command to show the game (fade it in)
- I added a second text colour value:   --c-text-flipped: #ffffff; that I applied to  .row[data-state="correct"] .tile {} and in the @keyframes {} sections for the 50% and 100% values. This way you can, for example, have a white background colour for the tiles with black text colour, and then when the tiles flip and have either grey, yellow or green background colour, their font colour changes to white (like the real Wordle game).

**Comment by Poodmund** [comment]
https://github.com/BlackyWhoElse/streamer.bot-actions/pull/71 A couple of the things mentioned above as a PR

**Comment by BlackyWhoElse** [comment]
I removed the keyboard so the widget would be smaller.
There could be an optional setting that reenables that?

About the Hide and show, that could be solved by streamer.bot with a action to toggle visibilty of the source.

**Comment by BlackyWhoElse** [comment]
Pland features:
- Adding definitions of words.
> Adding a definition to the variables that can be used in Streamer.bot
- Community word
> On a x second interval the most guessed word will be enter into wordle. A top 3 words display would be displayed for better understanding.
