### ISSUE TITLE
[General Usage Question] Stream Labels

### ISSUE THREAD

**Issue by KitPickles** [BlackyWhoElse/streamer.bot-actions#72]
Hello! 

I have a quick question regarding Stream Labels and how they work. I have everything imported into Streamer.bot but that's about as far as I was able to get. In case you can't tell, I'm fairly new to this... 😂

Do the actions labeled "Event" get added to the corresponding events under the Platforms tab? Also, does this have to run under a specific websocket because the !SL command doesn't seem to fire on WS 5. I haven't tried on 4 because I don't want to risk breaking anything else. Any help or direction would be greatly appreciated!

**Comment by KitPickles** [comment]
Hi @BlackyWhoElse!

Wow, thanks for the fast reply! Please don't feel the need to hurry on. I appreciate you taking a look at it. In the meantime, I'll keep playing with it because I think there may be some issues on my end in general. That might be related to !SL not working. Thanks again! 

All the best,
Kit

**Comment by BlackyWhoElse** [comment]
Hey @KitPickles 
Sorry it took so long but I got a beta version for you to test if you like. 

I will send you the details in a discord pm later this day.

**Comment by KitPickles** [comment]
Good morning! No need to apologize at all! You've been busy with everything in this package and it's all so much fun to play with and learn from. 😀

I'm at work know so I don't know what my full discord ID is, but I'm in the Streamer.bot server under the same name. Thanks for thinking of me for testing out the features!

**Comment by BlackyWhoElse** [comment]
#44 Merging this issue into the dev issue
