### ISSUE TITLE
[Bug] who's that pokemon poll not auto Closing

### ISSUE THREAD

**Issue by MumbleMarvin** [BlackyWhoElse/streamer.bot-actions#74]
### To Reproduce
Start a game via WTP - Start Game (Poll)
Vote and wait till poll ends
Pokemon is revealed in poll but not in chat and not in source

### Expected behavior
Pokemon should be shown and should be announced in chat

### Additional context
Ending via WTP - End Game anounces the winner and hides the source

**Comment by BlackyWhoElse** [comment]
Fixed in next release [a326cad](https://github.com/BlackyWhoElse/streamer.bot-actions/commit/a326cad7a606673c8fbe922f033abeee139c4165)
