### ISSUE TITLE
[Bug] Chat doesnt show Redemptions for custom Text input

### ISSUE THREAD

**Issue by MumbleMarvin** [BlackyWhoElse/streamer.bot-actions#75]
### Describe the bug
Redeeming a custom redeem with message will just show the message in chat nothing more

### To Reproduce
Create a Redemption that requires a Text. 

### Expected behavior
Should look like the redeem of the default "highlight my message" Redeem

### Screenshots
![image](https://user-images.githubusercontent.com/96959222/213275067-daa0c37b-6487-4a8a-bd63-4edbd56d7c2f.png)
![image](https://user-images.githubusercontent.com/96959222/213275113-185076e5-394a-49a1-9433-152e4ada3f4b.png)

**Comment by Ik1497** [comment]
The Streamer.bot Websocket doesn't give the text entered in redemptions so it can't show it

**Comment by BlackyWhoElse** [comment]
True. But there are still some display errors. Will be fixed in the next patch.

**Comment by BlackyWhoElse** [comment]
For reference this is what we are working with :)
``` js
Object { 
  id: "2bc9f15d-403d-4b7d-b575-f03b10c7acaf", 
  user_id: "27638012", 
  user_login: "blackywersonst", 
  user_name: "Blackywersonst", 
  user_input: "asdasdasd",
  status: "unfulfilled",
  reward: {
    cost: 1,
    id: "4420517d-6695-41b7-b7e5-6cc8346b83e5",
    prompt: "Guess the 5-letter word",
    title: "Guess the word",
  },
  redeemed_at: "2023-01-19T09:37:21.828621Z" 
}
```

**Comment by BlackyWhoElse** [comment]
Works for me. In all themes

**Comment by BlackyWhoElse** [comment]
https://github.com/BlackyWhoElse/streamer.bot-actions/releases/tag/v0.3.3.2
