### ISSUE TITLE
[Feature] Delete old messages if a new one goes beyond the viewport

### ISSUE THREAD

**Issue by f1amy** [BlackyWhoElse/streamer.bot-actions#79]
### Problem
When there are too many recent messages in chat, the oldest one could become clipped as the height of the widget's viewport is not enough to fit all of the messages.

### Describe the solution you'd like
Chat should calculate the height of the viewport and if after showing the new message the total height of all messages is more than the total height of the viewport, remove as many old messages as necessary to fit a new message.

### Additional context
Don't know this should work with custom themes, because custom CSS could mess up the way to calculate the height of a message.
Coming from nightbot chat widget which has this feature.

**Comment by BlackyWhoElse** [comment]
Hey @f1amy 
That could be done by CSS. 
Could you add some example screenshots :)

**Comment by f1amy** [comment]
Hello @BlackyWhoElse, I don't think that this is possible with only CSS
I will come later with an example

**Comment by f1amy** [comment]
Here is an example of how it should look like
https://user-images.githubusercontent.com/27062841/225370158-608592d3-b92a-46bd-a525-8b5846e5e330.mp4
Notice what happens to the messages at the top when the screen is already filled with messages, it gradually fades out with an animation.

**Comment by f1amy** [comment]
WIP code based on nightbot's widget
![image](https://user-images.githubusercontent.com/27062841/225371119-d4c9e80e-13ac-4d71-beb7-41d49aece63b.png)

```js
.then(() => {
    //Prevent clipping
    var currentHeight = 0;
    $("[#chat](https://vk.com/im?sel=160615960&st=%23chat)").children().each(function () {
        currentHeight += $(this).outerHeight(true);
    });
    var parentHeight = $('[#chat](https://vk.com/im?sel=160615960&st=%23chat)').outerHeight(true);
    var count = 0;
    var $chatLine, lineHeight;
    while (currentHeight > parentHeight) {
        $chatLine = $('.msg').eq(count);
        lineHeight = $chatLine.outerHeight(true);

        $chatLine.animate(
            {
                "margin-top": -lineHeight
            },
            100,
            function () {
                $(this).remove();
            }
        );

        currentHeight -= lineHeight;
        count++;
    }
})
```

**Comment by BlackyWhoElse** [comment]
Ah yeah, that's another way to do it.
Will be added in the next release
