### ISSUE TITLE
streamerbot start with pc how?

### ISSUE THREAD

**Issue by mrharryhd** [BlackyWhoElse/streamer.bot-actions#85]
streamerbot start with pc how?

**Comment by chrispiciullo** [comment]
This probably isn't the right place for that question but... Follow this guide. Works for Windows 10 and 11: [How to Add a Program to Startup in Windows 10 or Windows 11](https://www.howtogeek.com/208224/how-to-add-a-program-to-startup-in-windows/)

**Comment by BlackyWhoElse** [comment]
Hello @mrharryhd 
You can add StreamerBot to the Windows startup cycle, as mentioned by @chrispiciullo.
This is not an official Streamerbot repo, so I'm closing this topic.
