### ISSUE TITLE
[Bug] Youtube messages dont hide

### ISSUE THREAD

**Issue by BlackyWhoElse** [BlackyWhoElse/streamer.bot-actions#87]
### Describe the bug
I'm trying to use the bubbles theme, but YouTube messages don't obey the hide delay. They just stay on screen.
https://discord.com/channels/834650675224248362/905128013140754452/1180943067080040470

### Example
https://clips.twitch.tv/DullStupidReindeerHotPokket-ZAWdpVBHXbycIPRQ

**Comment by Sinistral2099** [comment]
Works perfectly again! This can be closed.
