### ISSUE TITLE
Widget Chat not working with YouTube [Bug] 

### ISSUE THREAD

**Issue by eldemiandx** [BlackyWhoElse/streamer.bot-actions#94]
YouTube chat doesn't work, but Twitch chat does.

I haven't made any modifications, I just tried starting a stream on YouTube (public) and no message appears while it does in StreamerBot Chat. Twitch chat works correctly.

**Comment by BlackyWhoElse** [comment]
Hey sorry for the inconvenience. I will take a look at it tomorrow

**Comment by BlackyWhoElse** [comment]
Hey just created a new release with a fix for your problem
I tested it on a short stream and it worked for me. 

Please give me feedback on this issue if it continuous 
https://github.com/BlackyWhoElse/streamer.bot-actions/releases/tag/v.0.4.0-beta_3
