### ISSUE TITLE
Twitch/YouTube emblem

### ISSUE THREAD

**Issue by eldemiandx** [BlackyWhoElse/streamer.bot-actions#99]
For Chat Widget:

Add a Twitch/Youtube icon next to the name depending on where the message comes from, just like streamer.bot does
![imagen](https://github.com/BlackyWhoElse/streamer.bot-actions/assets/126356606/4af6bac7-85bd-40b7-8de3-7a999b38c56c)

**Comment by BlackyWhoElse** [comment]
Hey @eldemiandx You could do that via the template files.
But you're right that it would be cool to have them already stored in the badge variable for themes. 

Todo:
- [ ] Add streaming platform badge to badge variable
- [ ] Add platform images to css/image
- [ ] PlatformBadge: add true/false to settings.json

**Comment by BlackyWhoElse** [comment]
![image](https://github.com/BlackyWhoElse/streamer.bot-actions/assets/2930941/0328a78f-7271-4bd6-9b58-869383c5e3cd)
##  Update
- Added settings.platformBadge
- Added images/platform/{platform}.png
- Added CSS .badges .{platform}
  - This is so themes can use custom badges for platforms if needed

**Comment by BlackyWhoElse** [comment]
Needs testing with youtube buti will close it for now
